// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAI(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AskAI'](arg1, arg2, arg3, arg4);
}

export function BroadcastLog(arg1) {
  return window['go']['main']['App']['BroadcastLog'](arg1);
}

export function DeleteConfigValue(arg1, arg2) {
  return window['go']['main']['App']['DeleteConfigValue'](arg1, arg2);
}

export function ExecuteScript(arg1) {
  return window['go']['main']['App']['ExecuteScript'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function PingHost(arg1) {
  return window['go']['main']['App']['PingHost'](arg1);
}

export function RankDirectory(arg1) {
  return window['go']['main']['App']['RankDirectory'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function ScanPorts(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScanPorts'](arg1, arg2, arg3, arg4);
}

export function SetConfigValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetConfigValue'](arg1, arg2, arg3);
}

export function StoreDelete(arg1, arg2) {
  return window['go']['main']['App']['StoreDelete'](arg1, arg2);
}

export function StoreGet(arg1, arg2) {
  return window['go']['main']['App']['StoreGet'](arg1, arg2);
}

export function StoreList(arg1) {
  return window['go']['main']['App']['StoreList'](arg1);
}

export function StorePut(arg1, arg2, arg3) {
  return window['go']['main']['App']['StorePut'](arg1, arg2, arg3);
}
