// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AskAI(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function BroadcastLog(arg1:string):Promise<void>;

export function DeleteConfigValue(arg1:string,arg2:string):Promise<void>;

export function ExecuteScript(arg1:string):Promise<string>;

export function GetConfig():Promise<main.AppConfig>;

export function GetLogs():Promise<Array<string>>;

export function GetSystemStats():Promise<main.SystemStats>;

export function PingHost(arg1:string):Promise<string>;

export function RankDirectory(arg1:string):Promise<Array<main.DiskEntry>>;

export function ResetConfig():Promise<void>;

export function ScanPorts(arg1:string,arg2:Array<number>,arg3:number,arg4:number):Promise<Array<number>>;

export function SetConfigValue(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StoreDelete(arg1:string,arg2:string):Promise<void>;

export function StoreGet(arg1:string,arg2:string):Promise<string>;

export function StoreList(arg1:string):Promise<Record<string, string>>;

export function StorePut(arg1:string,arg2:string,arg3:string):Promise<void>;
