// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecuteScript(arg1:string):Promise<string>;

export function GetSystemStats():Promise<main.SystemStats>;

export function PingHost(arg1:string):Promise<string>;

export function ScanDirectoryForLargeFiles(arg1:string,arg2:number):Promise<Array<main.LargeFileInfo>>;

export function ScanPorts(arg1:string,arg2:Array<number>):Promise<Array<number>>;
