// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteScript(arg1) {
  return window['go']['main']['App']['ExecuteScript'](arg1);
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function PingHost(arg1) {
  return window['go']['main']['App']['PingHost'](arg1);
}

export function ScanDirectoryForLargeFiles(arg1, arg2) {
  return window['go']['main']['App']['ScanDirectoryForLargeFiles'](arg1, arg2);
}

export function ScanPorts(arg1, arg2) {
  return window['go']['main']['App']['ScanPorts'](arg1, arg2);
}
